In [1]:
import pandas as pd
df= pd.read_csv('players.csv')

In [2]:
df.head(1)

Player       Team         Role  Last5Runs  Last5Wickets  AvgRuns  \
0  G. Maxwell  Australia  All-rounder         52             1     52.2   

   AvgWickets Fitness  RecentForm  Runs  Wickets  FantasyScore  
0         1.6   Unfit          60    44        1            69

In [3]:
df.drop('Player', axis= 'columns',inplace=True)
df.drop('Team', axis= 'columns',inplace=True)

In [4]:
df.head(1)

Role  Last5Runs  Last5Wickets  AvgRuns  AvgWickets Fitness  \
0  All-rounder         52             1     52.2         1.6   Unfit   

   RecentForm  Runs  Wickets  FantasyScore  
0          60    44        1            69

In [5]:
df.drop('Role', axis= 'columns',inplace=True)

In [6]:
df.head(1)

Last5Runs  Last5Wickets  AvgRuns  AvgWickets Fitness  RecentForm  Runs  \
0         52             1     52.2         1.6   Unfit          60    44   

   Wickets  FantasyScore  
0        1            69

In [16]:
df['Fitness']=df['Fitness'].apply(lambda x: 1 if x=='Fit'  else 0)

In [17]:
x= df.drop('FantasyScore',axis= 'columns')
y= df['FantasyScore']

In [18]:
x

Last5Runs  Last5Wickets  AvgRuns  AvgWickets  Fitness  RecentForm  Runs  \
0           52             1     52.2         1.6        0          60    44   
1           57             1     57.6         1.0        0          51    56   
2           64             0     64.8         0.0        0          76    70   
3           28             0     28.2         0.0        0          74    20   
4           62             0     62.6         0.0        0          82    63   
..         ...           ...      ...         ...      ...         ...   ...   
495         45             1     45.8         1.4        0          79    44   
496         23             0     23.4         0.0        0          62    27   
497         39             0     39.2         0.0        0          53    53   
498         65             1     65.4         1.4        0          83    49   
499         47             0     47.8         0.0        0          50    47   

     Wickets  
0          1  
1          2  
2          0  
3          0  
4          1  
..       ...  
495        1  
496        0  
497        1  
498        0  
499        1  

[500 rows x 8 columns]

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
model=LinearRegression()

In [21]:
import numpy as np

In [22]:
model.fit(x,y)

LinearRegression()

In [23]:
df.columns

Index(['Last5Runs', 'Last5Wickets', 'AvgRuns', 'AvgWickets', 'Fitness',
       'RecentForm', 'Runs', 'Wickets', 'FantasyScore'],
      dtype='object')

In [24]:
model.predict([[90,2,178.9, 100.8,1,80,70,2]])

C:\Users\Ishita Sharma\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([820.14173098])

In [25]:
model.predict([[45,0,78.9, 19.8,0,50,40,1]])

C:\Users\Ishita Sharma\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([205.33225243])

In [26]:
m= model.coef_

In [27]:
m

array([-5.73686182e-01, -9.90476498e-01,  6.76053917e-01,  6.50255520e+00,
        8.88178420e-15,  2.00553431e-02,  9.21859993e-01,  2.00364868e+01])

In [28]:
c=model.intercept_

In [30]:
m1= m[0]
m2= m[1]
m3= m[2]
m4= m[3]
m5= m[4]
m6= m[5]
m7= m[6]
m8= m[7]


In [31]:
m1*100+m2*180+m3*29+m4*35+m5*1+m6*53+m7*6+m8*52 +c

1051.175243742599